version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: crypto-pltf-db-container
    environment:
      MYSQL_ROOT_PASSWORD: aclapp1
      MYSQL_DATABASE: crypto-pltf
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
